### ISSUE TITLE
Issue after rolling back migration

### ISSUE THREAD

**Issue by oscardelben** [macourtney/Conjure#1]
Hi, I was following the hello world tutorial and I had an issue after rolling back the database to version 0. The problem is that after a rollback, I can't migrate again because I receive this error:

http://pastie.org/720041

To fix this I had to remove the data directory.

**Comment by macourtney** [comment]
schema_info exists
Current database version: 0
Updating to version: 1
Running 001_create_posts.clj up...
Update counts:
 Statement 0: EXECUTE_FAILED
BatchUpdateException:
 Message: null
 SQLState: null
 Error Code: 0
Exception in thread "main" java.lang.Exception: transaction rolled back: null (NO_SOURCE_FILE:0)
    at clojure.lang.Compiler.eval(Compiler.java:4543)
    at clojure.lang.Compiler.load(Compiler.java:4857)
    at clojure.lang.Compiler.load(Compiler.java:4833)
    at clojure.core$load_reader__4297.invoke(core.clj:2322)
    at clojure.core$load_string__4300.invoke(core.clj:2330)
    at conjure.migration.runner$run_migrate_up__380.invoke(runner.clj:50)
    at conjure.migration.runner$migrate_up_all__390.invoke(runner.clj:82)
    at conjure.migration.runner$migrate_up__400.invoke(runner.clj:105)
    at conjure.migration.runner$update_to_version__410.invoke(runner.clj:135)
    at conjure.migration.runner$update_to_version__410.invoke(runner.clj:127)
    at migrate$eval__562.invoke(migrate.clj:25)
    at clojure.lang.Compiler.eval(Compiler.java:4532)
    at clojure.lang.Compiler.load(Compiler.java:4857)
    at clojure.lang.Compiler.loadFile(Compiler.java:4824)
    at clojure.main$load_script__5833.invoke(main.clj:206)
    at clojure.main$script_opt__5864.invoke(main.clj:258)
    at clojure.main$main__5888.doInvoke(main.clj:333)
    at clojure.lang.RestFn.invoke(RestFn.java:413)
    at clojure.lang.Var.invoke(Var.java:346)
    at clojure.lang.AFn.applyToHelper(AFn.java:173)
    at clojure.lang.Var.applyTo(Var.java:463)
    at clojure.main.main(main.java:39)
Caused by: java.lang.Exception: transaction rolled back: null
    at clojure.contrib.sql.internal$throw_rollback__6772.invoke(internal.clj:136)
    at clojure.contrib.sql.internal$transaction_STAR___6775.invoke(internal.clj:158)
    at clojure.contrib.sql$do_commands__6797.doInvoke(sql.clj:85)
    at clojure.lang.RestFn.invoke(RestFn.java:413)
    at clojure.contrib.sql$create_table__6813.doInvoke(sql.clj:115)
    at clojure.lang.RestFn.applyTo(RestFn.java:144)
    at clojure.core$apply__3243.doInvoke(core.clj:390)
    at clojure.lang.RestFn.invoke(RestFn.java:443)
    at flavors.h2$create_table__240$fn__242.invoke(h2.clj:105)
    at clojure.contrib.sql.internal$with_connection_STAR___6758.invoke(internal.clj:98)
    at flavors.h2$create_table__240.doInvoke(h2.clj:104)
    at clojure.lang.RestFn.applyTo(RestFn.java:147)
    at clojure.core$apply__3243.doInvoke(core.clj:390)
    at clojure.lang.RestFn.invoke(RestFn.java:443)
    at conjure.model.database$create_table__342.doInvoke(database.clj:46)
    at clojure.lang.RestFn.invoke(RestFn.java:477)
    at migrate.001_create_posts$up__571.invoke(001_create_posts.clj:11)
    at migrate$eval__577.invoke(Unknown Source)
    at clojure.lang.Compiler.eval(Compiler.java:4532)
    ... 21 more
Caused by: java.sql.BatchUpdateException
    at org.h2.jdbc.JdbcStatement.executeBatch(JdbcStatement.java:626)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:88)
    at clojure.lang.Reflector.invokeNoArgInstanceMember(Reflector.java:263)
    at clojure.contrib.sql$do_commands__6797$fn__6800.invoke(sql.clj:86)
    at clojure.contrib.sql.internal$transaction_STAR___6775.invoke(internal.clj:154)
    ... 38 more

**Comment by macourtney** [comment]
I've been able to migrate up and down all the time using the tutorial. I can't reproduce this issue.
