### ISSUE TITLE
problem with getting started

### ISSUE THREAD

**Issue by sandys** [macourtney/Conjure#2]
hi,
   Unfortunately your how-to is a bit lacking : I did not know I had to change to the "conjure" directory inside the top-level directory before copying the project.clj

Secondly, there's a problem with using it. After creating a "hi" directory, I get the following project.clj:
(defproject hi "1.0.0-SNAPSHOT"
  :description "This is the hi project."
  :dependencies [[org.clojure/clojure "1.1.0"]
                 [org.clojure/clojure-contrib "1.1.0"]
                 [conjure-core "0.7.0-SNAPSHOT"]]
  :dev-dependencies [[lein-conjure "0.7.0-SNAPSHOT"]]

  :main run)

running ./conjure.sh server gives errors

Exception in thread "main" java.lang.IllegalStateException: I/O in transaction (execute.clj:0)
        at clojure.lang.Compiler.eval(Compiler.java:4658)
        at clojure.lang.Compiler.load(Compiler.java:4972)
        at clojure.lang.Compiler.loadFile(Compiler.java:4939)
        at clojure.main$load_script__7405.invoke(main.clj:213)
        at clojure.main$script_opt__7442.invoke(main.clj:265)
        at clojure.main$main__7466.doInvoke(main.clj:346)
        at clojure.lang.RestFn.invoke(RestFn.java:426)
        at clojure.lang.Var.invoke(Var.java:363)
        at clojure.lang.AFn.applyToHelper(AFn.java:175)
        at clojure.lang.Var.applyTo(Var.java:476)
        at clojure.main.main(main.java:37)
Caused by: java.lang.IllegalStateException: I/O in transaction
        at clojure.contrib.sql.internal$transaction_STAR___7362.invoke(internal.clj:157)
        at clojure.contrib.sql$do_commands__7390.doInvoke(sql.clj:89)
        at clojure.lang.RestFn.invoke(RestFn.java:413)
        at clojure.contrib.sql$create_table__7430.doInvoke(sql.clj:119)
        at clojure.lang.RestFn.applyTo(RestFn.java:144)
        at clojure.core$apply__4370.invoke(core.clj:438)

This is on Ubuntu 10.10 with Sun Java hi,
   Unfortunately your how-to is a bit lacking : I did not know I had to change to the "conjure" directory inside the top-level directory before copying the project.clj

Secondly, there's a problem with using it. After creating a "hi" directory, I get the following project.clj:
(defproject hi "1.0.0-SNAPSHOT"
  :description "This is the hi project."
  :dependencies [[org.clojure/clojure "1.1.0"]
                 [org.clojure/clojure-contrib "1.1.0"]
                 [conjure-core "0.7.0-SNAPSHOT"]]
  :dev-dependencies [[lein-conjure "0.7.0-SNAPSHOT"]]

  :main run)

running ./conjure.sh server gives errors

Exception in thread "main" java.lang.IllegalStateException: I/O in transaction (execute.clj:0)
        at clojure.lang.Compiler.eval(Compiler.java:4658)
        at clojure.lang.Compiler.load(Compiler.java:4972)
        at clojure.lang.Compiler.loadFile(Compiler.java:4939)
        at clojure.main$load_script__7405.invoke(main.clj:213)
        at clojure.main$script_opt__7442.invoke(main.clj:265)
        at clojure.main$main__7466.doInvoke(main.clj:346)
        at clojure.lang.RestFn.invoke(RestFn.java:426)
        at clojure.lang.Var.invoke(Var.java:363)
        at clojure.lang.AFn.applyToHelper(AFn.java:175)
        at clojure.lang.Var.applyTo(Var.java:476)
        at clojure.main.main(main.java:37)
Caused by: java.lang.IllegalStateException: I/O in transaction
        at clojure.contrib.sql.internal$transaction_STAR___7362.invoke(internal.clj:157)
        at clojure.contrib.sql$do_commands__7390.doInvoke(sql.clj:89)
        at clojure.lang.RestFn.invoke(RestFn.java:413)
        at clojure.contrib.sql$create_table__7430.doInvoke(sql.clj:119)
        at clojure.lang.RestFn.applyTo(RestFn.java:144)
        at clojure.core$apply__4370.invoke(core.clj:438)

This is on Ubuntu 10.10 with Sun Java "1.6.0_21"

Leiningen 1.3.1 on Java 1.6.0_21 Java HotSpot(TM) 64-Bit Server VM

**Comment by macourtney** [comment]
Are you using Leiningen to create your conjure project? You may want to use that on Ubuntu instead of the shell script. Though, I have no idea what's going on with the shell script based on the above exception.

**Comment by macourtney** [comment]
Closing old issue
